import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import './globals.css';

const notoSans = Noto_Sans_KR({
	subsets: ['latin', 'cyrillic'],
	weight: ['300', '400', '500', '700'],
	display: 'swap',
	variable: '--font-noto-sans'
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={notoSans.variable}>
				{children}
			</body>
		</html>
	);
}
